In [1]:
import numpy as np
import pprint

In [9]:
def information_Array(array):
    print(array)
    print(type(array))
    print(array.dtype)# le type de chaque élément
    print(array.shape)# x lignes y colonnes
    print(array.size)# x * y 
    return 0;

In [11]:
array = np.array([[1,2,3],[2,3,4]],dtype = np.int64)
print(array)
print(type(array))
print(array.dtype)# le type de chaque élément
print(array.shape)# 2 lignes 3 colonnes
print(array.size)# 2 * 3 = 6

[[1 2 3]
 [2 3 4]]
<class 'numpy.ndarray'>
int64
(2, 3)
6


### Modifier DType

In [10]:
array1 = np.array([2,23,2],dtype = np.float64)
information_Array(array1)

[ 2. 23.  2.]
<class 'numpy.ndarray'>
float64
(3,)
3


0

### Commun forms for array: 

###### shape(a,b)

In [14]:
a0 = np.zeros((2,3),dtype = np.int64)
print(a0)

[[0 0 0]
 [0 0 0]]


In [15]:
a1 = np.ones((3,4),dtype = np.int64)
print(a1)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [16]:
arrayEmpty = np.empty((3,4))
print(arrayEmpty)

[[0.00000000e+000 1.48219694e-323 0.00000000e+000 1.77229088e-310]
 [3.50977866e+064 0.00000000e+000 0.00000000e+000             nan]
 [            nan 3.50977942e+064 6.93871497e-310 0.00000000e+000]]


### numpy.arange(a) 生成一行range(a) 规则符合générateur range的规则

In [17]:
array10 = np.arange(11)
print(array10)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [20]:
arrayPaire = np.arange(0,21,2)
print(arrayPaire)

[ 0  2  4  6  8 10 12 14 16 18 20]


### numpy.arange(a).reshape(3,4) ---(par exemple) 

In [22]:
arrayPaire1 = np.arange(0,30,2).reshape(3,5)
print(arrayPaire1)

[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]]


In [26]:
arrayLise = np.arange(1,11,3).reshape(2,2)
print(arrayLise)
arrayLise = np.linspace(1,10,4).reshape(2,2)
print(arrayLise)

[[ 1  4]
 [ 7 10]]
[[ 1.  4.]
 [ 7. 10.]]


### Calcul

##### la même dimension

In [30]:
a = np.arange(10,41,10)
b = np.arange(1,5)
c = a + b
d = a-b
d1 = b-a
print(c)
print(d)
print(d1)

[11 22 33 44]
[ 9 18 27 36]
[ -9 -18 -27 -36]


##### Dimension différente

In [39]:
matrice1 = np.arange(1,11).reshape(2,5)
print("Matrice1 = ")
print(matrice1)
matrice2 = np.arange(1,6)
print("Matrice2 = ")
print(matrice2)
matrice3 = matrice1 + matrice2
print("Matrice1 + Matrice2 = ")
print(matrice3)
matrice4 = matrice1*matrice2
print("Matrice1 * Matrice2 = ")
print(matrice4)
matrice4 = matrice1.dot(matrice2)# np.dot遵循Matrice乘法原则
print("Matrice1 x Matrice2 = ")
print(matrice4)
matrice4 = np.dot(matrice1,matrice2)# np.dot遵循Matrice乘法原则
print("Matrice1 x Matrice2 = ")
print(matrice4)
matrice5 = matrice1 / matrice2
print("Matrice1 / Matrice2 = ")
print(matrice5)

Matrice1 = 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Matrice2 = 
[1 2 3 4 5]
Matrice1 + Matrice2 = 
[[ 2  4  6  8 10]
 [ 7  9 11 13 15]]
Matrice1 * Matrice2 = 
[[ 1  4  9 16 25]
 [ 6 14 24 36 50]]
Matrice1 x Matrice2 = 
[ 55 130]
Matrice1 x Matrice2 = 
[ 55 130]
Matrice1 / Matrice2 = 
[[1.         1.         1.         1.         1.        ]
 [6.         3.5        2.66666667 2.25       2.        ]]


### Comparaison

In [44]:
print(matrice1)
matriceInferieur100 = matrice1 < 100
print(matriceInferieur100)
print(matrice1)
matriceInferieur7 = matrice1 < 7
print(matriceInferieur7)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ True  True  True  True  True]
 [ True  True  True  True  True]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ True  True  True  True  True]
 [ True False False False False]]


### Random with array

###### np.random.random([shape, shape])

In [47]:
import random
from random import random
arrayRandom33 = np.random.random([3,3])
print(arrayRandom33)
arrayRandom24 = np.random.random([2,4])
print(arrayRandom24)

[[0.97357916 0.44087616 0.7279016 ]
 [0.95248063 0.78912761 0.14983472]
 [0.2710954  0.04721158 0.36807306]]
[[0.26748946 0.25798544 0.13682714 0.47697304]
 [0.91343778 0.12243688 0.36558493 0.40032778]]


### Max min sum with array

In [59]:
arrayTest = np.arange(10,201,10).reshape(4,5)
print(arrayTest)
Max = np.max(arrayTest)
print(type(Max))
Min = np.min(arrayTest)
Sum = np.sum(arrayTest)
print("Le plus grand élément dans la matrice? ",Max)
print("Le pluis petit élément dans la matrice? ",Min)
print("La somme de tous les éléments: ",Sum)
print("------------------")
print(arrayTest)
MaxLigne = np.max(arrayTest,axis=0)
print(type(MaxLigne))
MinLigne = np.min(arrayTest,axis=0)
SumLigne = np.sum(arrayTest,axis=0)
print("La plus grande ligne dans la matrice? ",MaxLigne)
print("La plus petite ligne dans la matrice? ",MinLigne)
print("La somme de toutes les lignes en une ligne",SumLigne)
print("------------------")
print(arrayTest)
MaxLigne = np.max(arrayTest,axis=1)
print(type(MaxLigne))
MinLigne = np.min(arrayTest,axis=1)
SumLigne = np.sum(arrayTest,axis=1)
print("La plus grande colonne dans la matrice? ",MaxLigne)
print("La plus petite colonne dans la matrice? ",MinLigne)
print("La somme de toutes les colonnes en une ligne",SumLigne)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]]
<class 'numpy.int64'>
Le plus grand élément dans la matrice?  200
Le pluis petit élément dans la matrice?  10
La somme de tous les éléments:  2100
------------------
[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]]
<class 'numpy.ndarray'>
La plus grande ligne dans la matrice?  [160 170 180 190 200]
La plus petite ligne dans la matrice?  [10 20 30 40 50]
La somme de toutes les lignes en une ligne [340 380 420 460 500]
------------------
[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]]
<class 'numpy.ndarray'>
La plus grande colonne dans la matrice?  [ 50 100 150 200]
La plus petite colonne dans la matrice?  [ 10  60 110 160]
La somme de toutes les colonnes en une ligne [150 400 650 900]


### Statistiques Max Min Average Médian

In [99]:
a = [[2, 4, 8, 9], [1, 7, 4, 5], [5, 7, 1, 4]]
a = np.array(a)
print(a)
print("Le plus grand élément dans a : ")
Max = np.max(a)
print(Max)
print("Le plus petit élément dans a : ")
Min = np.min(a)
print(Min)
print("La moyenne de chaque élément")
Moyenne = np.average(a)
print(Moyenne)
print("La médian de chaque élément")
Médian = np.median(a)
print(Médian)
print("------------")
print("Les plus grands éléments dans chaque colonne")
MaxColonne = a.max(axis=0)
print(MaxColonne)
print("Les plus petits éléments dans chaque colonne")
MinColonne = a.min(axis=0)
print(MinColonne)
print("Range pour chaque colonne")
RangeColonne = a.ptp(axis=0)
print(RangeColonne)
print("------------")
print("Les plus grands éléments dans chaque ligne")
MaxLigne = a.max(axis=1)
print(MaxLigne)
print("Les plus petits éléments dans chque ligne")
MinLigne = a.min(axis=1)
print(MinLigne)
print("Range pour chaque ligne")
RangeLigne = a.ptp(axis = 1)
print(RangeLigne)

[[2 4 8 9]
 [1 7 4 5]
 [5 7 1 4]]
Le plus grand élément dans a : 
9
Le plus petit élément dans a : 
1
La moyenne de chaque élément
4.75
La médian de chaque élément
4.5
------------
Les plus grands éléments dans chaque colonne
[5 7 8 9]
Les plus petits éléments dans chaque colonne
[1 4 1 4]
Range pour chaque colonne
[4 3 7 5]
------------
Les plus grands éléments dans chaque ligne
[9 7 7]
Les plus petits éléments dans chque ligne
[2 1 1]
Range pour chaque ligne
[7 6 6]


### Sort

In [64]:
array = np.arange(14,2,-1).reshape(3,4)
print(array)
ordre = np.sort(array)#从小到大排列,array本身不改变
print(ordre)
print(array)

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
[[11 12 13 14]
 [ 7  8  9 10]
 [ 3  4  5  6]]
[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]


In [65]:
a = np.array([[2, 6, 0, 4],[4, 8, 9, 1],[10, 2, 3, 11]])
print(a)
ordre = np.sort(a)
print(a)
print(ordre)

[[ 2  6  0  4]
 [ 4  8  9  1]
 [10  2  3 11]]
[[ 2  6  0  4]
 [ 4  8  9  1]
 [10  2  3 11]]
[[ 0  2  4  6]
 [ 1  4  8  9]
 [ 2  3 10 11]]


### Transpose

In [73]:
array = np.arange(0,20,2).reshape(2,5)
arrayTransposer = np.transpose(array)
print(arrayTransposer)
arrayTransposer = array.T
print(arrayTransposer)

[[ 0 10]
 [ 2 12]
 [ 4 14]
 [ 6 16]
 [ 8 18]]
[[ 0 10]
 [ 2 12]
 [ 4 14]
 [ 6 16]
 [ 8 18]]


### Clip

###### Clip(a,5,9) 小于5的等于5，大于9的等于9

In [76]:
array=np.arange(21).reshape(3,7)
print(array)
arrayClip = np.clip(array,5,9)
print(arrayClip)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]]
[[5 5 5 5 5 5 6]
 [7 8 9 9 9 9 9]
 [9 9 9 9 9 9 9]]


### Average Median 

In [82]:
print(array)
Moyenne = np.average(array)
print(Moyenne)
Médian = np.median(array)
print(Médian)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]]
10.0
10.0


### Indexing

###### 找到最大值的index

In [113]:
a = np.arange(1,101).reshape(10,10)
print(a)
Max_a = np.max(a)
Max_a_Position = np.argmbax(a)
print("Maximum-----",Max_a," Position-----",Max_a_Position)
Min_a = np.min(a)
Min_a_Position = np.argmin(a)
print("Minimum-----",Min_a," Position-----",Min_a_Position)
Max_ligne = a.max(1)
Max_ligne_Position = a.argmax(1)
print("Maximums de Chaque ligne en array:\n",Max_ligne," \nPosition dans la ligne:\n",Max_ligne_Position)
Max_colonne = a.max(0)
Max_colonne_Position = a.argmax(0)
print("Maximums de Chaque ligne en array:\n",Max_colonne," \nPosition dans la colonne:\n",Max_colonne_Position)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
Maximum----- 100  Position----- 99
Minimum----- 1  Position----- 0
Maximums de Chaque ligne en array:
 [ 10  20  30  40  50  60  70  80  90 100]  
Position dans la ligne:
 [9 9 9 9 9 9 9 9 9 9]
Maximums de Chaque ligne en array:
 [ 91  92  93  94  95  96  97  98  99 100]  
Position dans la colonne:
 [9 9 9 9 9 9 9 9 9 9]


### 遍历

In [21]:
a = np.arange(1,21).reshape(4,5)
print(a,'\n')
print("a[0] = \n",a[0])# La première ligne
print("a[1] = \n",a[1])# La deuxième Ligne
print("a[:][1] = \n",a[:][1])# La deuxième ligne
print("a[1:3] = \n",a[1:3])# Les deuxième et troisième lignes
print("a[1][1] = \n",a[1][1])# Le deuxième élément de la deuxième ligne. La même logique 
print("a[1,1] = \n",a[1,1])# Le deuxième élément de la deuxième ligne
print("a[:,1] = \n",a[:,1])# La deuxième colonne
print("a[:,1:2] = \n",a[:,1:2])# La deuxième colonne
print("a[:,1:3] = \n",a[:,1:3])# Les deuxième et troisième colonnes
print("a[1,1:3] = \n",a[1,1:3])# Les deuxième et troisème éléments de la première ligne
print("a[:,0][1:3] = \n",a[:,0][1:3])# Les deuxième et troisième éléments de la première colonne
print("-----------------------")
for ligne in a:
    print(ligne,"\n")
print("      ")
for colonne in a.T:
    print(colonne,"\n")

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]] 

a[0] = 
 [1 2 3 4 5]
a[1] = 
 [ 6  7  8  9 10]
a[:][1] = 
 [ 6  7  8  9 10]
a[1:3] = 
 [[ 6  7  8  9 10]
 [11 12 13 14 15]]
a[1][1] = 
 7
a[1,1] = 
 7
a[:,1] = 
 [ 2  7 12 17]
a[:,1:2] = 
 [[ 2]
 [ 7]
 [12]
 [17]]
a[:,1:3] = 
 [[ 2  3]
 [ 7  8]
 [12 13]
 [17 18]]
a[1,1:3] = 
 [7 8]
a[:,0][1:3] = 
 [ 6 11]
-----------------------
[1 2 3 4 5] 

[ 6  7  8  9 10] 

[11 12 13 14 15] 

[16 17 18 19 20] 

      
[ 1  6 11 16] 

[ 2  7 12 17] 

[ 3  8 13 18] 

[ 4  9 14 19] 

[ 5 10 15 20] 



###  Trouver non-zéro


##### retourner shape

In [115]:
print(a)
print(np.nonzero(a))

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8,
       8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9]), array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1,
       2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3,
       4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5,
       6, 7,

### .copy()
array这个元素传递有点意思的，就是如果直接a=b，其实从内存角度来考虑就相当于a和b指向了一样的元素内存空间，所以改变一个元素的值，另一个一样改变，如果想各是各的，并且还想传递另一个元素的值那就用a=b.copy()，所以这个还是需要注意的

In [125]:
a = np.arange(11)
b = a
a1 = a.copy()
print("a = ",id(a),a)
print("b = ",id(b),b)
print("a1 = ",id(a1),a1)
a[1]=4
print("a = ",id(a),a)
print("b = ",id(b),b)
print("a1 = ",id(a1),a1)

a =  4836021872 [ 0  1  2  3  4  5  6  7  8  9 10]
b =  4836021872 [ 0  1  2  3  4  5  6  7  8  9 10]
a1 =  4766081952 [ 0  1  2  3  4  5  6  7  8  9 10]
a =  4836021872 [ 0  4  2  3  4  5  6  7  8  9 10]
b =  4836021872 [ 0  4  2  3  4  5  6  7  8  9 10]
a1 =  4766081952 [ 0  1  2  3  4  5  6  7  8  9 10]


### Vectorisation 

flattern

In [24]:
a = np.arange(1,21).reshape(4,5)
print(a)
b = a.flatten()
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


### Merge

In [34]:
a = np.array([[1,2,2],[2,2,3]])
b = np.arange(4,10).reshape(2,3)
print(a)
print(b)
vertical = np.vstack((a,b))
print(vertical)
horizontal = np.hstack((a,b))
print(horizontal)
Multi = np.concatenate((a,b),axis=1)
print(Multi)
Multi1 = np.concatenate((a,b,b),axis = 0)
print(Multi1)

[[1 2 2]
 [2 2 3]]
[[4 5 6]
 [7 8 9]]
[[1 2 2]
 [2 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 2 4 5 6]
 [2 2 3 7 8 9]]
[[1 2 2 4 5 6]
 [2 2 3 7 8 9]]
[[1 2 2]
 [2 2 3]
 [4 5 6]
 [7 8 9]
 [4 5 6]
 [7 8 9]]


### Découper

In [47]:
a = np.arange(1,21).reshape(4,5)
b = np.array_split(a,2,axis=0)
print(b)
c = np.array_split(a,3,axis=1)
print(c)

[array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]]), array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])]
[array([[ 1,  2],
       [ 6,  7],
       [11, 12],
       [16, 17]]), array([[ 3,  4],
       [ 8,  9],
       [13, 14],
       [18, 19]]), array([[ 5],
       [10],
       [15],
       [20]])]


### Exercice 

Soit M = 

###### (1 1 0 0
######  0 1 1 0
######  0 0 1 1
######  0 0 0 1)
Calculer M**n n>=3

In [2]:
a = np.array([[1,1,0,0],[0,1,1,0],[0,0,1,1],[0,0,0,1]])
print(a)

[[1 1 0 0]
 [0 1 1 0]
 [0 0 1 1]
 [0 0 0 1]]


In [5]:
m=a.dot(a)
print("m**2 = \n")
print(m)

m**2 = 

[[1 2 1 0]
 [0 1 2 1]
 [0 0 1 2]
 [0 0 0 1]]


In [7]:
for i in range(3,10):
    print("m**",i,'\n')
    m = m.dot(a)
    print(m)

m** 3 

[[ 1  7 21 35]
 [ 0  1  7 21]
 [ 0  0  1  7]
 [ 0  0  0  1]]
m** 4 

[[ 1  8 28 56]
 [ 0  1  8 28]
 [ 0  0  1  8]
 [ 0  0  0  1]]
m** 5 

[[ 1  9 36 84]
 [ 0  1  9 36]
 [ 0  0  1  9]
 [ 0  0  0  1]]
m** 6 

[[  1  10  45 120]
 [  0   1  10  45]
 [  0   0   1  10]
 [  0   0   0   1]]
m** 7 

[[  1  11  55 165]
 [  0   1  11  55]
 [  0   0   1  11]
 [  0   0   0   1]]
m** 8 

[[  1  12  66 220]
 [  0   1  12  66]
 [  0   0   1  12]
 [  0   0   0   1]]
m** 9 

[[  1  13  78 286]
 [  0   1  13  78]
 [  0   0   1  13]
 [  0   0   0   1]]
